services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - USER=${USER}
      - PASS=${PASSWORD}
    volumes:
      - ./config:/config
      - /data/transmission/downloads:/downloads
      - /data/transmission/watch:/watch
    ports:
      - 8170:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
